"""Standalone digital qudit and multi-torus search simulator."""

from .core import (
    QuditState,
    RankedState,
    SearchStage,
    TorusSearchResult,
    basis_state,
    coordinates_to_index,
    diffusion_operator,
    dual_round_trip_error,
    fourier_transform,
    index_to_coordinates,
    local_fourier_transform,
    optimal_search_iterations,
    phase_gate,
    phase_oracle,
    search_torus_register,
    shift_gate,
    tensor_product,
    uniform_state,
)

__all__ = [
    "QuditState",
    "SearchStage",
    "RankedState",
    "TorusSearchResult",
    "basis_state",
    "uniform_state",
    "shift_gate",
    "phase_gate",
    "fourier_transform",
    "tensor_product",
    "coordinates_to_index",
    "index_to_coordinates",
    "local_fourier_transform",
    "dual_round_trip_error",
    "phase_oracle",
    "diffusion_operator",
    "optimal_search_iterations",
    "search_torus_register",
]
